"""Added description to Exercises

Revision ID: 02223d41de13
Revises: 148e4bb98972
Create Date: 2024-03-13 11:27:38.481423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02223d41de13'
down_revision = '148e4bb98972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
