"""empty message

Revision ID: 148e4bb98972
Revises: 8c4f7fe8b2fa
Create Date: 2024-03-13 11:25:38.608437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148e4bb98972'
down_revision = '8c4f7fe8b2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
