"""Updated reference in Exercise to User

Revision ID: adb916517c64
Revises: a31da5847b8d
Create Date: 2024-03-12 15:46:04.107426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb916517c64'
down_revision = 'a31da5847b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercises',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='user_exercises_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_exercises_user_id_fkey')
    )
    # ### end Alembic commands ###
